[package]
name = "ejdict_rs_core"
version = "0.1.0"
authors = ["tomo3110 <uotias64_mole@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
