[package]
name = "ejdict_rs_core"
version = "0.0.1"
authors = ["tomo3110 <uotias64_mole@yahoo.co.jp>"]

edition = "2018"

[dependencies]
failure = "0.1"
serde = { version = "1", features = ["derive"] }
